"""Framework-independent failure-calibrated OPD primitives."""

from .chunk_parser import ChunkMasks, parse_response_chunks
from .conditions import Condition, ConditionInputs, build_condition_inputs
from .loss import FCOPDLossConfig, compute_fc_opd_loss, sparse_forward_kl
from .offline_loss import (
    MinTrainReport,
    MinTrainStep,
    OfflineLossResult,
    OfflineLossSmokeReport,
    OfflineRecordTensors,
    load_offline_score_records,
    make_student_logits,
    offline_record_to_tensors,
    run_offline_loss_backward,
    run_offline_loss_smoke,
    run_offline_min_train_smoke,
)
from .real_student_smoke import (
    HFStudentProvider,
    RealMinTrainReport,
    RealMinTrainStep,
    RealStudentConfig,
    RealStudentResult,
    RealStudentSmokeReport,
    StudentForwardOutput,
    condition_inputs_from_record,
    detect_tied_parameter_groups,
    lm_head_embed_tied,
    response_logit_slice,
    run_real_student_min_train,
    run_real_student_record,
    run_real_student_smoke,
    teacher_scores_to_device,
)
from .offline_scoring import (
    ByteTokenizer,
    OfflineScoreRecord,
    OfflineScoringConfig,
    OfflineScoringResult,
    build_condition_inputs_for_record,
    default_output_dir,
    iter_offline_scores,
    load_student_responses,
    load_vision_opd_records,
    make_smoke_dataset,
    score_record,
    write_offline_scores,
)
from .router import RouterConfig, route_condition_weights
from .signal_decomposer import TeacherTopK, compute_condition_signals, jensen_shannon_topk
from .teacher_client import TeacherClient, score_teacher_conditions
from .teacher_protocol import (
    TeacherMetadata,
    TeacherScoreRequest,
    TeacherScoreResponse,
    tokenizer_fingerprint,
)
from .teacher_prompts import render_teacher_prompt

__all__ = [
    "ByteTokenizer",
    "ChunkMasks",
    "Condition",
    "ConditionInputs",
    "FCOPDLossConfig",
    "HFStudentProvider",
    "MinTrainReport",
    "RealMinTrainReport",
    "RealMinTrainStep",
    "MinTrainStep",
    "OfflineLossResult",
    "OfflineLossSmokeReport",
    "OfflineRecordTensors",
    "OfflineScoreRecord",
    "OfflineScoringConfig",
    "OfflineScoringResult",
    "RealStudentConfig",
    "RealStudentResult",
    "RealStudentSmokeReport",
    "RouterConfig",
    "StudentForwardOutput",
    "TeacherTopK",
    "TeacherClient",
    "TeacherMetadata",
    "TeacherScoreRequest",
    "TeacherScoreResponse",
    "build_condition_inputs",
    "build_condition_inputs_for_record",
    "compute_condition_signals",
    "compute_fc_opd_loss",
    "condition_inputs_from_record",
    "default_output_dir",
    "detect_tied_parameter_groups",
    "iter_offline_scores",
    "jensen_shannon_topk",
    "lm_head_embed_tied",
    "load_offline_score_records",
    "load_student_responses",
    "load_vision_opd_records",
    "make_smoke_dataset",
    "make_student_logits",
    "offline_record_to_tensors",
    "parse_response_chunks",
    "run_offline_loss_backward",
    "run_offline_loss_smoke",
    "run_offline_min_train_smoke",
    "render_teacher_prompt",
    "response_logit_slice",
    "route_condition_weights",
    "run_real_student_min_train",
    "run_real_student_record",
    "run_real_student_smoke",
    "score_record",
    "score_teacher_conditions",
    "sparse_forward_kl",
    "teacher_scores_to_device",
    "tokenizer_fingerprint",
    "write_offline_scores",
]
